api_platform:
    title: HELLOWORLD API
    version: 1.0.0
    graphql:
        graphiql:
            enabled: false
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
